const KEYS={sessions:'workRate.sessions.v1',categories:'workRate.categories.v1',timer:'workRate.timer.v1'};
const defaults=['Form Boards','Wire Cutting','Crimping','Harness Assembly','Testing','Other'];
const $=id=>document.getElementById(id);
let sessions=read(KEYS.sessions,[]),categories=read(KEYS.categories,defaults),timer=read(KEYS.timer,{status:'idle',startedAt:null,accumulatedMs:0,category:'Form Boards'}),tick;
function read(k,fallback){try{const v=JSON.parse(localStorage.getItem(k));return v??fallback}catch{return fallback}}
function write(k,v){localStorage.setItem(k,JSON.stringify(v))}
function esc(v=''){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function elapsed(){return timer.accumulatedMs+(timer.status==='running'&&timer.startedAt?Date.now()-timer.startedAt:0)}
function hms(ms){const s=Math.max(0,Math.floor(ms/1000)),h=Math.floor(s/3600),m=Math.floor(s%3600/60);return [h,m,s%60].map(n=>String(n).padStart(2,'0')).join(':')}
function duration(ms){const mins=Math.round(ms/60000);if(mins<1)return '<1 min';if(mins<60)return `${mins} min`;const h=Math.floor(mins/60),m=mins%60;return m?`${h}h ${m}m`:`${h}h`}
function rate(q,ms){return q>0&&ms>0?q/(ms/3600000):0} function minUnit(q,ms){return q>0?ms/60000/q:0}
function fmt(n,d=1){return Number.isFinite(n)?n.toFixed(d):'—'}
function saveTimer(){write(KEYS.timer,timer)}
function toast(msg){$('toast').textContent=msg;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),1800)}
function pluralCategory(name,q){if(q===1&&name.endsWith('s'))return name.slice(0,-1);return name}

function renderSelects(){const opts=categories.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');$('categorySelect').innerHTML=opts;$('summaryCategory').innerHTML=opts;$('historyFilter').innerHTML='<option value="all">All categories</option>'+opts;if(categories.includes(timer.category))$('categorySelect').value=timer.category;else{timer.category=categories[0];saveTimer()}$('liveRateUnit').textContent=`${timer.category}/hour`}
function renderTimer(){const ms=elapsed();$('timerDisplay').textContent=hms(ms);const running=timer.status==='running',paused=timer.status==='paused';$('startBtn').classList.toggle('hidden',running||paused);$('pauseBtn').classList.toggle('hidden',!running&&!paused);$('pauseBtn').textContent=paused?'▶ RESUME':'Ⅱ PAUSE';$('finishBtn').disabled=timer.status==='idle'||ms<1000;$('categorySelect').disabled=timer.status!=='idle';$('runStatus').classList.toggle('running',running);$('runStatus').innerHTML=`<i></i> ${running?'RUNNING':paused?'PAUSED':'READY'}`;renderLiveRate()}
function renderLiveRate(){const q=parseFloat($('liveQuantity').value)||0,r=rate(q,elapsed());$('liveRate').textContent=r?fmt(r):'—'}
function start(){timer={status:'running',startedAt:Date.now(),accumulatedMs:0,category:$('categorySelect').value};saveTimer();renderTimer();tick=setInterval(renderTimer,250)}
function pauseResume(){if(timer.status==='running'){timer.accumulatedMs=elapsed();timer.startedAt=null;timer.status='paused';clearInterval(tick)}else{timer.startedAt=Date.now();timer.status='running';tick=setInterval(renderTimer,250)}saveTimer();renderTimer()}
function finish(){const ms=elapsed();if(ms<1000)return;timer.accumulatedMs=ms;if(timer.status==='running')clearInterval(tick);timer.status='paused';timer.startedAt=null;saveTimer();openSessionDialog({durationMs:ms,category:timer.category,quantity:$('liveQuantity').value,name:$('liveName').value,notes:$('liveNotes').value})}
function resetTimer(){timer={status:'idle',startedAt:null,accumulatedMs:0,category:$('categorySelect').value};saveTimer();$('liveQuantity').value=0;$('liveName').value='';$('liveNotes').value='';renderTimer()}

function openSessionDialog(data,isEdit=false){$('editId').value=data.id||'';$('dialogEyebrow').textContent=isEdit?'EDIT ENTRY':'FINISH SESSION';$('dialogTitle').textContent=isEdit?'Correct session details':'Save your work';$('dialogTime').textContent=hms(data.durationMs);$('dialogTime').dataset.ms=data.durationMs;$('dialogCategory').textContent=data.category;$('dialogQuantity').value=data.quantity||'';$('dialogName').value=data.name||'';$('dialogNotes').value=data.notes||'';updateDialogCalc();$('sessionDialog').showModal();setTimeout(()=>$('dialogQuantity').focus(),80)}
function updateDialogCalc(){const q=parseFloat($('dialogQuantity').value)||0,ms=Number($('dialogTime').dataset.ms);$('dialogRate').textContent=q?fmt(rate(q,ms)):'—';$('dialogMinutes').textContent=q?fmt(minUnit(q,ms)):'—'}
function saveSession(e){e.preventDefault();const q=parseFloat($('dialogQuantity').value),ms=Number($('dialogTime').dataset.ms),id=$('editId').value; if(!(q>0)){toast('Enter a quantity above zero');return}const existing=sessions.find(s=>s.id===id);const item={id:id||crypto.randomUUID(),createdAt:existing?.createdAt||new Date().toISOString(),category:$('dialogCategory').textContent,durationMs:ms,quantity:q,name:$('dialogName').value.trim(),notes:$('dialogNotes').value.trim()};if(id)sessions=sessions.map(s=>s.id===id?item:s);else sessions.unshift(item);write(KEYS.sessions,sessions);$('sessionDialog').close();if(!id)resetTimer();renderAll();toast(id?'Entry updated':'Session saved')}
function entryHTML(s){const r=rate(s.quantity,s.durationMs);return `<button class="entry-card" data-entry="${s.id}" type="button"><span class="entry-title">${esc(s.name||s.category)}</span><span class="entry-rate">${fmt(r)}<small>${esc(s.category)}/hr</small></span><span class="entry-meta">${new Date(s.createdAt).toLocaleDateString(undefined,{month:'short',day:'numeric'})} · ${duration(s.durationMs)} · ${s.quantity} ${esc(pluralCategory(s.category,s.quantity))}</span>${s.notes?`<span class="entry-note">${esc(s.notes)}</span>`:''}</button>`}
function renderHistory(){const recent=sessions.slice(0,3);$('recentList').innerHTML=recent.length?recent.map(entryHTML).join(''):'<div class="empty">Your completed sessions will appear here.</div>';const f=$('historyFilter').value||'all',items=f==='all'?sessions:sessions.filter(s=>s.category===f);$('historyList').innerHTML=items.length?items.map(entryHTML).join(''):'<div class="empty">No sessions in this category yet.</div>';document.querySelectorAll('[data-entry]').forEach(b=>b.onclick=()=>openDetail(b.dataset.entry))}
function openDetail(id){const s=sessions.find(x=>x.id===id);if(!s)return;const r=rate(s.quantity,s.durationMs),m=minUnit(s.quantity,s.durationMs);$('detailContent').innerHTML=`<div class="dialog-head"><div><p class="eyebrow">${new Date(s.createdAt).toLocaleString([], {dateStyle:'medium',timeStyle:'short'})}</p><h2>${esc(s.name||s.category)}</h2></div><button class="icon-btn" id="closeDetail" aria-label="Close">×</button></div><div class="result-banner"><strong>${esc(s.category)}</strong><span>${duration(s.durationMs)}</span></div><div class="detail-grid"><div class="detail-box"><span>QUANTITY</span><strong>${s.quantity}</strong></div><div class="detail-box"><span>UNITS / HOUR</span><strong>${fmt(r)}</strong></div><div class="detail-box"><span>MIN / UNIT</span><strong>${fmt(m)}</strong></div><div class="detail-box"><span>ELAPSED</span><strong>${hms(s.durationMs)}</strong></div></div>${s.notes?`<p class="eyebrow">NOTES</p><div class="detail-notes">${esc(s.notes)}</div>`:''}<div class="detail-actions"><button class="btn" id="editEntry">EDIT</button><button class="btn danger" id="deleteEntry">DELETE</button></div>`;$('detailDialog').showModal();$('closeDetail').onclick=()=>$('detailDialog').close();$('editEntry').onclick=()=>{$('detailDialog').close();openSessionDialog(s,true)};$('deleteEntry').onclick=()=>{if(confirm('Delete this session? This cannot be undone.')){sessions=sessions.filter(x=>x.id!==id);write(KEYS.sessions,sessions);$('detailDialog').close();renderAll();toast('Entry deleted')}}}
function renderSummary(){const cat=$('summaryCategory').value||categories[0],items=sessions.filter(s=>s.category===cat),totalMs=items.reduce((a,s)=>a+s.durationMs,0),units=items.reduce((a,s)=>a+s.quantity,0),overall=rate(units,totalMs),best=items.reduce((b,s)=>Math.max(b,rate(s.quantity,s.durationMs)),0);$('summaryCards').innerHTML=`<div class="summary-card"><span>SESSIONS</span><strong>${items.length}</strong><small>completed</small></div><div class="summary-card"><span>TOTAL UNITS</span><strong>${fmt(units,units%1?1:0)}</strong><small>${esc(cat)}</small></div><div class="summary-card"><span>TOTAL TIME</span><strong>${duration(totalMs)}</strong><small>recorded</small></div><div class="summary-card accent"><span>BEST RATE</span><strong>${best?fmt(best):'—'}</strong><small>${esc(cat)}/hour</small></div><div class="summary-card wide-card accent"><span>OVERALL AVERAGE</span><strong>${overall?fmt(overall):'—'} <small>${esc(cat)}/hour</small></strong><small>${units?fmt(minUnit(units,totalMs)):'—'} minutes per unit</small></div>`}
function renderCategories(){ $('categoryList').innerHTML=categories.map(c=>`<div class="category-item"><span>${esc(c)}</span>${c==='Form Boards'?'':`<button data-delete-category="${esc(c)}" aria-label="Delete ${esc(c)}">×</button>`}</div>`).join('');document.querySelectorAll('[data-delete-category]').forEach(b=>b.onclick=()=>{const c=b.dataset.deleteCategory;if(sessions.some(s=>s.category===c)){toast('Delete its sessions first');return}categories=categories.filter(x=>x!==c);write(KEYS.categories,categories);renderSelects();renderCategories();renderAll()})}
function exportCSV(){const rows=[['Date','Category','Session Name','Elapsed Seconds','Elapsed Time','Quantity','Units per Hour','Minutes per Unit','Notes'],...sessions.map(s=>[s.createdAt,s.category,s.name,Math.round(s.durationMs/1000),hms(s.durationMs),s.quantity,fmt(rate(s.quantity,s.durationMs),3),fmt(minUnit(s.quantity,s.durationMs),3),s.notes])];const csv=rows.map(r=>r.map(v=>`"${String(v??'').replace(/"/g,'""')}"`).join(',')).join('\r\n'),blob=new Blob([csv],{type:'text/csv;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`work-rate-${new Date().toISOString().slice(0,10)}.csv`;a.click();URL.revokeObjectURL(a.href);toast('CSV downloaded')}
function changeView(view){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===view));document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===view));if(view==='historyView')renderHistory();if(view==='summaryView')renderSummary();scrollTo({top:0,behavior:'smooth'})}
function renderAll(){renderHistory();renderSummary();renderTimer()}

$('startBtn').onclick=start;$('pauseBtn').onclick=pauseResume;$('finishBtn').onclick=finish;$('closeSessionDialog').onclick=()=>$('sessionDialog').close();$('closeCategoryDialog').onclick=()=>$('categoryDialog').close();$('liveQuantity').oninput=renderLiveRate;$('plusQty').onclick=()=>{$('liveQuantity').value=(parseFloat($('liveQuantity').value)||0)+1;renderLiveRate()};$('minusQty').onclick=()=>{$('liveQuantity').value=Math.max(0,(parseFloat($('liveQuantity').value)||0)-1);renderLiveRate()};$('categorySelect').onchange=e=>{timer.category=e.target.value;saveTimer();$('liveRateUnit').textContent=`${timer.category}/hour`};$('dialogQuantity').oninput=updateDialogCalc;$('sessionForm').onsubmit=saveSession;$('historyFilter').onchange=renderHistory;$('summaryCategory').onchange=renderSummary;$('exportBtn').onclick=exportCSV;$('seeHistoryBtn').onclick=()=>changeView('historyView');document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>changeView(b.dataset.view));$('manageCategoriesBtn').onclick=()=>{renderCategories();$('categoryDialog').showModal()};$('addCategoryBtn').onclick=()=>{const c=$('newCategory').value.trim();if(!c)return;if(categories.some(x=>x.toLowerCase()===c.toLowerCase())){toast('Category already exists');return}categories.push(c);write(KEYS.categories,categories);$('newCategory').value='';renderSelects();renderCategories();toast('Category added')};
renderSelects();renderAll();if(timer.status==='running')tick=setInterval(renderTimer,250);document.addEventListener('visibilitychange',renderTimer);window.addEventListener('beforeunload',saveTimer);if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js');
